version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: pressure_monitor
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pressure_monitor
      SPRING_DATASOURCE_USERNAME: postgres_user
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres:5432/pressure_monitor
      SPRING_FLYWAY_USER: postgres_user
      SPRING_FLYWAY_PASSWORD: postgres
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      JWT_SECRET: coleaquiumsha256
      JWT_EXPIRATION_MILLISECONDS: 604800000
      SERVER_ADDRESS: 0.0.0.0
