CREATE TABLE public.pressures (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	systole int4 NOT NULL,
	diastole int4 NOT NULL,
	user_id int8 NOT NULL,
	created_at timestamp NOT NULL DEFAULT now(),
	updated_at timestamp NOT NULL DEFAULT now(),
	CONSTRAINT pressure_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX pressure_id_idx ON public.pressures USING btree (id);



ALTER TABLE public.pressures ADD CONSTRAINT pressure_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE ON UPDATE CASCADE;